### ISSUE TITLE
How to make an object prefer forward message than get variable from environment ?

### ISSUE THREAD

**Issue by Moligaloo** [IoLanguage/io#422]
for example, the Lobby has two object: `foo` and `bar`,  when `foo` has not slot named `"bar"`,  the result of `foo bar` will return `bar`, but I also defined `forward` slot for `foo`, I'd like `foo` object will forward message rather return the variable from environment, is there any way to do this?

**Comment by stevedekorte** [comment]
Hi Moligaloo, this is because forward() acts like doesNotRespond: in Smalltalk. That is, it only get messages that aren't found in the receiver's proto chain. Here's one way to do what I think you want:

Proxy := Object clone do(
    target ::= nil
    forward := method(
        args := call message argsEvaluatedIn(call sender)
        return "caught a message named '" .. call message name .. "' with arguments: " .. args
    )
    clone := Object getSlot("clone") // so we can still clone after removing out protos
)

Proxy setProtos(list())

bar := 123
realFoo := Object clone
proxyFoo := Proxy clone setTarget(realFoo)

writeln("realFoo bar = ", realFoo bar)
writeln("proxyFoo bar = ", proxyFoo bar)
