### ISSUE TITLE
New release of Io?

### ISSUE THREAD

**Issue by nathunsmitty** [IoLanguage/io#428]
Given that there have been a lot of new additions to the codebase since the [last official Io release in 2017](https://github.com/IoLanguage/io/releases/tag/2017.09.06), would it be possible to create a new tagged release soon? This would allow users from package managers such as Homebrew to take advantage of these newer features.

Related: Homebrew/homebrew-core#40082

**Comment by AlesTsurko** [comment]
I think Io isn't ready for a stable release, before we at least update documentation and fix [this](https://github.com/IoLanguage/eerie/issues/32). But I agree that we ready for a tagged release marked as unstable.

We should determine how we're going to version Io, because as per current release system, stability of releases isn't clear. We can move into semantic versioning or just provide a suffix to the current system (i.e. 2019.20.05-alpha).

Waiting for your thoughts, @stevedekorte

**Comment by stevedekorte** [comment]
@AlesTsurko Your suggestions sound good to me. Please feel free to push those.

**Comment by AlesTsurko** [comment]
@nathunsmitty @stevedekorte done.

**Comment by stevedekorte** [comment]
Thanks @AlesTsurko. And thanks to @nathunsmitty for the suggestion.
